
name: Coveralls.io

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage report to Coveralls.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    
    - run: npm ci
    
    - run: npm run build:js --if-present
   
    - name: node tests and coverage
      run: npm run coverage
    
    - name: send report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
